# Generated by Django 6.0.1 on 2026-01-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationhistory',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
